[package]
name = "brs-test"
version = "0.1.0"
authors = ["ns <n@nsu.pw>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
brs = { path = "../brs" }
